### ISSUE TITLE
spellSuggest, promises, and express

### ISSUE THREAD

**Issue by samartioli** [Wulf/nodehun#55]
spellSuggest does not behave as expected when the callback is wrapped in a promise. 

[I created a repo to demonstrate the issue](https://github.com/abeai/nodehun-promise-example)

**Comment by trofim24** [comment]
Very similar to nodejs/node#5691

**Comment by Wulf** [comment]
Hi @samartioli, thanks for reporting this and the great example you've setup! 

I was able to reproduce this on linux! I tested this with the new `nan` branch, and the bug was no longer present (the promise resolved just fine). Thus, this will be fixed in the next major version (nodehun@3.0.0).

In the next version, `spellSuggest` will no longer be present, only `spellSuggestions` is available. And this is renamed to `suggest` as per #37.

Below, I briefly outline some of the changes I made in order to test the `nan` branch here:

1. Switch to the `suggest` function, instead of `spellSuggest`. `origWord` isn't passed in currently, so I use the `utterance` parameter instead later on instead.
2. an array is always sent, so I had to check for `suggestion.length > 0`, instead of just `if(suggestion)`.
3. resolve to the first element in the array instead of the array.

```javascript
function spellSuggestPromise(utterance) {
    return new Promise(function(resolve, reject) {
        dict.suggest(utterance, function(err, correct, suggestion, origWord) { // 1
            console.log(err, correct, suggestion, origWord);
            if (err) {
                // return setImmediate(reject, error);
                return reject(error);
            }
            if (suggestion.length > 0) { // 2
                return resolve(suggestion[0]); // 3
                // return setImmediate(resolve, suggestion);
            }
            return resolve(utterance);
            // return setImmediate(resolve, origWord);
        });
    });
}

```

Again, thanks for your patience and time setting up `nodehun-promise-example`. :)

**Comment by ashutoshrishi** [comment]
I am currently experiencing this with the master branch, and resorting to using setImmediate for now. Should I be using the `nan` now ?

**Comment by Wulf** [comment]
@samartioli @ashutoshrishi @loretoparisi thanks for your patience everyone, Promises are embedded directly into the addon now in the `n-api` branch. They will be featured in `3.0.0` which should be released in the following few days.

If you're still around, please let me know if the new version fixes the issue:

```
npm i -S wulf/nodehun#n-api
```

**Comment by Wulf** [comment]
I got a chance to verify that this doesn't occur with Nodehun v3 on node version 10, 11 and 12.

I changed the definition of the `spellSuggestPromise` function in [samartioli's repository](https://github.com/abeai/nodehun-promise-example) to the following:
```
function spellSuggestPromise(utterance) {
    return dict.suggest(utterance)
}
```

Thanks again for reporting this in a detailed manner and making it easy for us to reproduce the error. I'm going to close this issue, but feel free to reopen it or continue the discussion.
