### ISSUE TITLE
Chrome extension: Nodehun in webpack

### ISSUE THREAD

**Issue by vahaknp** [Wulf/nodehun#84]
Hi! I'm trying to use this package through webpack and am running into issues including it. Granted, I'm new to the world of webpack, so I was wondering if I was making an obvious mistake or there's something fundamentally off in my approach.

Whenever I include the package in one of my files as such:
```
import { Nodehun } from 'nodehun';

const fs = require('fs');
const affix = fs.readFileSync('./dictionaries/armenian_western.aff');
const dictionary = fs.readFileSync('./dictionaries/armenian_western.dic');

const nodehun = new Nodehun.Nodehun(affix, dictionary);

export async function spellcheck(word: string): Promise<string[]> {
  const suggestions = await nodehun.suggest(word);
  console.log('word', word);
  console.log('suggestions:', suggestions);
  return suggestions;
}
```

and I build webpack, I get the following error:
```
ERROR in ./src/spellcheck.ts
Module not found: Error: Can't resolve 'nodehun' in '/Users/vpapazian/Documents/vahakn/armenianinternetproject/src'
 @ ./src/spellcheck.ts 60:27-45
 @ ./src/replace.ts
 @ ./src/contentscript/contentscript.ts
```

Any help would be very much appreciated!

**Comment by Wulf** [comment]
hey @vahaknp, hope things are well. 

Is it possible for you to push your code to github or a similar platform?

**Comment by vahaknp** [comment]
Hi @Wulf! Doing well, hope you are as well! Thank you for such a quick response, and sorry I haven't gotten back to you until now.

Here's my very much WIP code: https://github.com/vahaknp/armenianinternetproject/tree/spellcheck_nodehun

Any advice you can give would be super helpful – I'm very much a webpack beginner 😅

**Comment by vahaknp** [comment]
Could it be that I need to use a specific loader, such as https://github.com/ushu/node-addon-loader, because Nodehun uses `node-addon-api`?

**Comment by Wulf** [comment]
hey @vahaknp thanks for sharing your code :)

I recommend you bundle [NSpell](https://github.com/wooorm/nspell) with your chrome extension instead; it's almost a drop-in replacement for this library and is implemented completely in JavaScript. You'll miss out on native performance, but it should hopefully be fast enough.

Otherwise, I think there are a few hurdles to cross when dealing with native binaries and chrome extensions. I'm not sure if it'll be possible to just use the loader you linked. If it does work, you'd have to then compile a binary for every platform/arch you want to support and load in the appropriate binary.

**Comment by vahaknp** [comment]
Thanks for the response @Wulf ! 

I figured that as well, so I have a parallel branch where I use NSpell – I've run into one issue already (which I've reported https://github.com/wooorm/nspell/issues/27), but I think that one is probably much easier to solve than dealing with native binaries.

Another approach I was considering was calling C++ directly (through https://webassembly.org/ or whatever the current standard is).

**Comment by Wulf** [comment]
Hey @vahaknp, hope things going well. I'm going to close this issue but feel free to reopen it :)
